<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production packing list — TP Company Limited (Vigor Cement Shipunloader)
 * Source PDF: Packing List & Invoice referencing 3 quotes (103, 104, 111)
 * 5 commercial items merged with 5 packing dimension rows
 */
return [
    'key'                   => 'tp_vigor_packing',
    'customer_company'      => 'TP Company Limited',
    'related_proposal_keys' => [
        '3 - 2026 - OTMSQ - 103 - Suction Hose',
        '4 - 2026 - OTMSQ - 104',
        '11 - 2026 - OTMSQ - 111',
    ],
    'save_option'           => 'otmain_seed_packing_id',
    'packing' => [
        'document_title'       => 'Packing List & Invoice',
        'date'                 => '2026-03-01',
        'vessel'               => 'Vigor Cement Shipunloader',
        'consignee_name'       => 'TP Company Limited',
        'consignee_address'    => "Bumbwini\nP.O BOX 271 Zanzibar",
        'consignee_phone'      => '+255 777 093 955',
        'consignee_email'      => 'dheeraj@luckycement.co.tz',
        'purchaser_name'       => 'TP Company Limited',
        'purchaser_address'    => "Bumbwini\nP.O BOX 271 Zanzibar",
        'purchaser_phone'      => '+255 777 093 955',
        'purchaser_email'      => 'dheeraj@luckycement.co.tz',
        'contact_person_name'  => 'Dheeraj',
        'contact_person_email' => 'dheeraj@luckycement.co.tz',
        'contact_person_phone' => '+255 777 093 955',
        'adminnote'            => 'No re-export to Russia or Belarus in accordance with Article 12G of EU Regulation 833/2014.',
    ],
    'items' => [
        [
            'description'   => 'DN400 Rotating suction nozzle, complete assembly',
            'hs_code'       => '8483409090',
            'qty'           => 1,
            'unit_price'    => 23880.00,
            'taxrate'       => 0,
            'packing_qty'   => 1,
            'unit_type'     => 'box',
            'unit_label'    => 'Wooden Box',
            'length'        => 2630,
            'width'         => 860,
            'height'        => 1000,
            'gross_weight'  => 731,
            'net_weight'    => 661,
        ],
        [
            'description'   => 'Custom Made Suction hose: Size: DN400 x L5500mm.',
            'hs_code'       => '400942',
            'qty'           => 4,
            'unit_price'    => 4100.00,
            'taxrate'       => 0,
            'packing_qty'   => 4,
            'unit_type'     => 'other',
            'unit_label'    => 'Hose DN400',
            'length'        => 5500,
            'width'         => 600,
            'height'        => 600,
            'gross_weight'  => 2360,
            'net_weight'    => 2360,
        ],
        [
            'description'   => 'Custom Made Suction hose: Size: DN300 x L5500mm.',
            'hs_code'       => '400942',
            'qty'           => 1,
            'unit_price'    => 3500.00,
            'taxrate'       => 0,
            'packing_qty'   => 1,
            'unit_type'     => 'other',
            'unit_label'    => 'Hose DN300',
            'length'        => 5500,
            'width'         => 400,
            'height'        => 400,
            'gross_weight'  => 440,
            'net_weight'    => 440,
        ],
        [
            'description'   => 'Compensator DN350',
            'hs_code'       => '400942',
            'qty'           => 2,
            'unit_price'    => 860.00,
            'taxrate'       => 0,
            'packing_qty'   => 2,
            'unit_type'     => 'other',
            'unit_label'    => 'Compensator DN350',
            'length'        => 340,
            'width'         => 600,
            'height'        => 600,
            'gross_weight'  => 220,
            'net_weight'    => 220,
        ],
        [
            'description'   => 'Compensator DN400',
            'hs_code'       => '400942',
            'qty'           => 2,
            'unit_price'    => 945.00,
            'taxrate'       => 0,
            'packing_qty'   => 2,
            'unit_type'     => 'other',
            'unit_label'    => 'Compensator DN400',
            'length'        => 340,
            'width'         => 600,
            'height'        => 600,
            'gross_weight'  => 220,
            'net_weight'    => 220,
        ],
    ],
];
