<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production quotation — TP Company Limited (2025)
 * Source PDF: 2025-SQ-105- Vigor Shipunloader - Valves (25-10-2025)
 */
return [
    'key'                 => '6.2025-SQ-105-vigor-valves',
    'source_quote_number' => '6 - 2025 - SQ - 105 - Vigor Shipunloader - Valves',
    'aliases'             => [
        '6 - 2025 - SQ - 105 - Vigor Shipunloader - Valves',
        '2025-SQ-105- Vigor Shipunloader - Valves',
        '2025-SQ-105',
        '2025-SQ-105-Vigor Shipunloader - Valves',
        '6.2025-SQ-105- Vigor Shipunloader - Valves',
        'tp_sq_105_valves',
    ],
    'customer_company'    => 'TP Company Limited',
    'force_status'        => 3,
    'populate_tracker'    => true,
    'save_option'         => 'otmain_seed_proposal_6_2025_sq_105_vigor_valves',
    'tracker_updates'     => array_fill(0, 10, ['item_status' => 'pending', 'notes' => '', 'admin_notes' => '']),
    'proposal' => [
        'subject'              => 'Valves - Vigor Shipunloader - Quotation',
        'date'                 => '2025-10-25',
        'open_till'            => '2025-11-08',
        'status'               => 3,
        'rel_type'             => 'customer',
        'client_ref'           => 'Valves - Vigor Shipunloader',
        'quote_title'          => 'Vigor Shipunloader - Valves',
        'document_title'       => 'Quotation',
        'terms'                => '',
        'expiry_days'          => 14,
        'availability'         => '',
        'notes'                => '',
        'contact_person_name'  => 'S.A.Ibrahim',
        'contact_person_email' => 'sales@otmain.com',
        'contact_person_phone' => '+31618228651',
        'payment_terms_text'   => '50% in advance / 50% before delivery',
        'shipment_terms'       => 'EXW - Rotterdam sea transport can be arranged',
        'delivery_time'        => '30 days',
        'total_usd_display'    => '',
        'total_gold_display'   => '',
        'subtotal'             => 2516.25,
        'total_tax'            => 0,
        'total'                => 2516.25,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'show_quantity_as'     => 1,
        'allow_comments'       => 1,
        'newitems'             => [
            1 => [
                'description'      => 'Valve Size: DN350 PN10/16',
                'long_description' => "Body Dutile Iron with antirust coating in RAL 6038\nDisc CF3M\nSeat EPDM High Temp. 150 °C\nShaft SS431",
                'qty'              => 1,
                'rate'             => 580.24,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => 'Spare Seat EPDM High Temp. 150°C (DN350)',
                'long_description' => '',
                'qty'              => 2,
                'rate'             => 80.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'Valve Size: DN300 PN10/16',
                'long_description' => "Body Dutile Iron with antirust coating in RAL 6038\nDisc Hardox\nSeat EPDM High Temp. 150 °C\nShaft SS431",
                'qty'              => 1,
                'rate'             => 402.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => 'Spare Seat EPDM High Temp. 150°C (DN300)',
                'long_description' => '',
                'qty'              => 2,
                'rate'             => 70.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => 'Valve Size: DN250 PN10/16',
                'long_description' => "Body Dutile Iron with antirust coating in RAL 6038\nDisc CF8M\nSeat EPDM 120 °C\nShaft SS431",
                'qty'              => 1,
                'rate'             => 283.91,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 5,
            ],
            6 => [
                'description'      => 'Spare Seat EPDM 120 °C (DN250)',
                'long_description' => '',
                'qty'              => 2,
                'rate'             => 45.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 6,
            ],
            7 => [
                'description'      => 'Valve Size: DN200 PN10/16',
                'long_description' => "Body Dutile Iron with antirust coating in RAL 6038\nDisc CF8M\nSeat Viton\nShaft SS431",
                'qty'              => 1,
                'rate'             => 320.10,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 7,
            ],
            8 => [
                'description'      => 'Spare Seat Viton (DN200)',
                'long_description' => '',
                'qty'              => 2,
                'rate'             => 80.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 8,
            ],
            9 => [
                'description'      => 'Valve Size: DN150 PN10/16',
                'long_description' => "Body Dutile Iron with antirust coating in RAL 6038\nDisc CF8M\nSeat Viton\nShaft SS431",
                'qty'              => 1,
                'rate'             => 260.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 9,
            ],
            10 => [
                'description'      => 'Spare Seat Viton (DN150)',
                'long_description' => '',
                'qty'              => 2,
                'rate'             => 60.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 10,
            ],
        ],
    ],
];
