<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production quotation — TP Company Limited (2025)
 * Source folder: 8.2025-SQ-107- Vigor Shipunloader - Spare Parts
 * PDF OCR sometimes says PQ-107 — folder/official prefix is SQ-107.
 *
 * Full quotation €10.570,86 (VAT 0%). Later commercial invoices may revise compensator mix.
 */
return [
    'key'                 => '8.2025-SQ-107-vigor-spare-parts',
    'source_quote_number' => '8 - 2025 - SQ - 107 - Vigor Shipunloader - Spare Parts',
    'aliases'             => [
        '8 - 2025 - SQ - 107 - Vigor Shipunloader - Spare Parts',
        '2025-SQ-107- Vigor Shipunloader - Spare Parts',
        '2025-SQ-107',
        '2025-PQ-107- Vigor Shipunloader - Spare Parts', // OCR/invoice variant
        '2025-PQ-107',
        '8.2025-SQ-107- Vigor Shipunloader - Spare Parts',
        'tp_pq_107_spare',
    ],
    'customer_company'    => 'TP Company Limited',
    'force_status'        => 3,
    'populate_tracker'    => true,
    'save_option'         => 'otmain_seed_proposal_8_2025_sq_107_vigor_spare_parts',
    'tracker_updates'     => array_fill(0, 14, ['item_status' => 'pending', 'notes' => '', 'admin_notes' => '']),
    'proposal' => [
        'subject'              => 'Vigor Shipunloader - Spare Parts - Quotation',
        'date'                 => '2025-11-21',
        'open_till'            => '2025-12-19',
        'status'               => 3,
        'rel_type'             => 'customer',
        'client_ref'           => 'Spare Parts - Vigor Shipunloader',
        'quote_title'          => 'Vigor Shipunloader - Spare Parts',
        'document_title'       => 'Quotation',
        'terms'                => '',
        'expiry_days'          => 28,
        'availability'         => '',
        'notes'                => '',
        'contact_person_name'  => "Sha'Iez Ibrahim",
        'contact_person_email' => 's.ibrahim@otmain.com',
        'contact_person_phone' => '+31618228651',
        'payment_terms_text'   => '50% by Order / 50% Before Shipment',
        'shipment_terms'       => 'EXW - Shipment can be arranged',
        'delivery_time'        => '4 weeks',
        'total_usd_display'    => '',
        'total_gold_display'   => '',
        'subtotal'             => 10570.86,
        'total_tax'            => 0,
        'total'                => 10570.86,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'show_quantity_as'     => 1,
        'allow_comments'       => 1,
        'newitems'             => [
            1 => [
                'description'      => 'Valve (without actuator) Size: DN200',
                'long_description' => "Valves\nBody Dutile Iron with antirust coating in RAL 6038\nDisc CF8M\nSeat Viton\nShaft SS431",
                'qty'              => 2,
                'rate'             => 370.10,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => 'Spare Seat Viton',
                'long_description' => '',
                'qty'              => 4,
                'rate'             => 80.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'Valve (without actuator) Size: DN200',
                'long_description' => "Body Dutile Iron with antirust coating in RAL 6038\nDisc CF8M\nSeat Viton\nShaft SS431",
                'qty'              => 2,
                'rate'             => 281.60,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => 'Spare Seat Viton',
                'long_description' => '',
                'qty'              => 4,
                'rate'             => 60.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => '5-Port Solenoid Valve SY9000 Series',
                'long_description' => '',
                'qty'              => 2,
                'rate'             => 121.80,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 5,
            ],
            6 => [
                'description'      => 'One Set proportional directional valves block assembled, Without solenoids',
                'long_description' => 'Hydraulics',
                'qty'              => 1,
                'rate'             => 2336.92,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 6,
            ],
            7 => [
                'description'      => 'Twin solenoid for proportional directional valves',
                'long_description' => '',
                'qty'              => 1,
                'rate'             => 142.88,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 7,
            ],
            8 => [
                'description'      => 'Seal kit for valve section SL 3',
                'long_description' => '',
                'qty'              => 1,
                'rate'             => 91.84,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 8,
            ],
            9 => [
                'description'      => 'Sealkit for connection block PSL BG 3',
                'long_description' => '',
                'qty'              => 1,
                'rate'             => 68.32,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 9,
            ],
            10 => [
                'description'      => 'Alternative Hydropack Oil Reservior Breather Filter',
                'long_description' => '',
                'qty'              => 1,
                'rate'             => 186.10,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 10,
            ],
            11 => [
                'description'      => 'Temprature Sensor 4-20mA, scale 0-150 degree',
                'long_description' => 'Vacuum',
                'qty'              => 3,
                'rate'             => 257.60,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 11,
            ],
            12 => [
                'description'      => 'Waterpump and Cooling Pump',
                'long_description' => '',
                'qty'              => 1,
                'rate'             => 1260.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 12,
            ],
            13 => [
                'description'      => 'Compensator DN350',
                'long_description' => '',
                'qty'              => 4,
                'rate'             => 860.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 13,
            ],
            14 => [
                'description'      => 'Algen dissolver',
                'long_description' => '',
                'qty'              => 3,
                'rate'             => 55.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 14,
            ],
        ],
    ],
];
