<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production quotation — Suriname Shiphandling & Services NV
 * Source PDF: 15 - 2026 - OTMSQ - 115 - Spare Part - Henna-T (22-06-2026)
 *
 * Spare Parts - Henna-T: wear protection, pilot valves, compensators, etc.
 */
return [
    'key'                 => 'tp_otmsq_115',
    'source_quote_number' => '15 - 2026 - OTMSQ - 115 - Spare Part - Henna-T',
    'customer_company'    => 'Suriname Shiphandling & Services NV',
    'force_status'        => 3, // Accepted
    'populate_tracker'    => true,
    'save_option'         => 'otmain_seed_proposal_tp_otmsq_115',
    'tracker_updates'     => array_fill(0, 17, ['item_status' => 'pending', 'notes' => '', 'admin_notes' => '']),
    'proposal' => [
        'subject'              => 'Spare Parts - Henna-T - Quotation',
        'date'                 => '2026-06-22',
        'open_till'            => '2026-07-19',
        'status'               => 3,
        'rel_type'             => 'customer',
        'client_ref'           => 'wear protection solution and clamps solenoid valve',
        'quote_title'          => 'Spare Part - Henna-T',
        'document_title'       => 'Quotation',
        'terms'                => '',
        'expiry_days'          => 27,
        'availability'         => '',
        'notes'                => '',
        // PDF deal contact (optional override)
        'contact_person_name'  => 'S.A.Ibrahim',
        'contact_person_email' => 's.ibrahim@otmain.com',
        'contact_person_phone' => '+316****8651',
        'payment_terms_text'   => '50% in advance<br />50% before delivery',
        'shipment_terms'       => 'EXW (Ex Works)',
        'delivery_time'        => '6 weeks',
        'total_usd_display'    => '$ 17.954,49',
        'total_gold_display'   => '',
        'subtotal'             => 15208.04,
        'total_tax'            => 0,
        'total'                => 15208.04,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'show_quantity_as'     => 1,
        'allow_comments'       => 1,
        'newitems'             => [
            1 => [
                'description'      => 'Pneumatic wear protection solution 10 kg',
                'long_description' => 'Features:
• High temperature resistance up to 232 °C (450 °F)
• Excellent abrasion resistance against fine particles
• Non-sagging formulation, suitable for vertical and overhead applications
• Easy to apply for maintenance and repair work

Spare Parts - Henna-T',
                'qty'              => 1,
                'rate'             => 1184,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => '2623077 - Norgeren 5/2 Pilot Valve including 24v Coil, High Volume, 10mm hose connection',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 10,
                'rate'             => 240,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'Hose Connector (for 5/2 Pilot Valve)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 20,
                'rate'             => 2.85,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => 'Silencer Filter (for 5/2 Pilot Valve)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 20,
                'rate'             => 3.20,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => 'Damper Regulator (for 5/2 Pilot Valve)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 20,
                'rate'             => 3.75,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 5,
            ],
            6 => [
                'description'      => '2623079 - Norgeren 3/2 Pilot Valve including 24v Coil, High Volume, 10mm hose connection',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 3,
                'rate'             => 211.55,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 6,
            ],
            7 => [
                'description'      => 'Hose Connector (for 3/2 Pilot Valve)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 3,
                'rate'             => 2.85,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 7,
            ],
            8 => [
                'description'      => 'Silencer Filter (for 3/2 Pilot Valve)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 3,
                'rate'             => 3.20,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 8,
            ],
            9 => [
                'description'      => 'Damper Regulator (for 3/2 Pilot Valve)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 3,
                'rate'             => 3.75,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 9,
            ],
            10 => [
                'description'      => 'MH510701G 5/2 Pilot Valve including 24v Coil, 8mm hose connection',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 2,
                'rate'             => 125,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 10,
            ],
            11 => [
                'description'      => 'Hose Connector (for MH510701G)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 24,
                'rate'             => 2.70,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 11,
            ],
            12 => [
                'description'      => 'Silencers filters (for MH510701G)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 24,
                'rate'             => 3.80,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 12,
            ],
            13 => [
                'description'      => '(Repair) Coupling for Blower Line DN150, OD: 168.3',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 5,
                'rate'             => 271.60,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 13,
            ],
            14 => [
                'description'      => 'Compensator DN350 Custom made for Abrasive Powders - Length: 340mm',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 7,
                'rate'             => 790,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 14,
            ],
            15 => [
                'description'      => 'Compensator DN200 Custom made for Abrasive Powders - Length: 340mm',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 2,
                'rate'             => 710,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 15,
            ],
            16 => [
                'description'      => 'P&ID Tag 21-10 and 22-10 - Valve DN80 including Positioner (4-20 mA), Rubber Seal: Silicone red (client ref.: Booster Valves)',
                'long_description' => 'Spare Parts - Henna-T',
                'qty'              => 2,
                'rate'             => 1100,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 16,
            ],
            17 => [
                'description'      => 'Discount for delayed offer due to absence caused by private circumstances',
                'long_description' => '',
                'qty'              => 1,
                'rate'             => -150,
                'unit'             => 'unit',
                'taxname'          => [],
                'order'            => 17,
            ],
        ],
    ],
];
