<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production invoice — Suriname Shiphandling & Services NV
 * Source: 2026-INV-115 REVISED (supersedes earlier €7.284)
 * Quote Ref → tp_otmsq_115
 */
return [
    'key'                   => 'sr_inv_115',
    'source_invoice_number' => '2026-INV-115 - Spare Parts - Henna-T - REVISED',
    'source_quote_ref'      => '15 - 2026 - OTMSQ - 115 - Spare Part - Henna-T',
    'related_proposal_key'  => 'tp_otmsq_115',
    'customer_company'      => 'Suriname Shiphandling & Services NV',
    'force_status'          => 1,
    'save_option'           => 'otmain_seed_invoice_sr_inv_115',
    'invoice' => [
        'number'               => 115,
        'date'                 => '2026-07-06',
        'duedate'              => '2026-03-21',
        'expiry_days'          => 0,
        'status'               => 1,
        'document_title'       => 'Commercial Invoice',
        'invoice_title'        => 'Spare Parts - Henna-T - REVISED',
        'adminnote'            => '',
        'contact_person_name'  => 'Widia Lestari - Ibrahim',
        'contact_person_email' => 'w.lestari@otmain.com',
        'contact_person_phone' => '+31620020563',
        'payment_terms_text'   => '50% advance payment<br />50% before to shipment',
        'delivery_terms'       => 'Lead time: 6 weeks',
        'lead_time'            => '',
        'delivery_address'     => "",
        'availability'         => '',
        'notes'                => 'The price is based on EXW terms; air freight or sea freight costs will be calculated and included in the second invoice.',
        'total_usd_display'    => '$ 9.136,78',
        'bank_account'         => 'USD',
        'show_quantity_as'     => 1,
        'sale_agent'           => 0,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'adjustment'           => 0,
        'clientnote'           => '',
        'terms'                => '',
        'newitems'             => [
            1 => [
                'description'      => 'Pneumatic wear protection solution 10 kg Bucket',
                'long_description' => "Spare Parts - Henna-T",
                'qty'              => 1,
                'rate'             => 1184.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => 'Norgeren 5/2 Pilot Valve including 24v Coil,',
                'long_description' => "",
                'qty'              => 10,
                'rate'             => 240.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'Hose Connector',
                'long_description' => "",
                'qty'              => 20,
                'rate'             => 2.85,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => 'Silencer Filter',
                'long_description' => "",
                'qty'              => 20,
                'rate'             => 3.20,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => 'Damper Regulator',
                'long_description' => "",
                'qty'              => 20,
                'rate'             => 3.75,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 5,
            ],
            6 => [
                'description'      => '2623079 - Norgeren 3/2 Pilot Valve including 24v',
                'long_description' => "",
                'qty'              => 3,
                'rate'             => 211.55,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 6,
            ],
            7 => [
                'description'      => 'Hose Connector',
                'long_description' => "",
                'qty'              => 3,
                'rate'             => 2.85,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 7,
            ],
            8 => [
                'description'      => 'Silencer Filter',
                'long_description' => "",
                'qty'              => 3,
                'rate'             => 3.20,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 8,
            ],
            9 => [
                'description'      => 'Damper Regulator',
                'long_description' => "",
                'qty'              => 3,
                'rate'             => 3.75,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 9,
            ],
            10 => [
                'description'      => 'MH510701G 5/2 Pilot Valve including 24v',
                'long_description' => "",
                'qty'              => 2,
                'rate'             => 125.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 10,
            ],
            11 => [
                'description'      => 'Hose Connector',
                'long_description' => "",
                'qty'              => 24,
                'rate'             => 2.70,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 11,
            ],
            12 => [
                'description'      => 'Silencer Filter',
                'long_description' => "",
                'qty'              => 24,
                'rate'             => 3.80,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 12,
            ],
            13 => [
                'description'      => '(Repair) Coupling for Blower Line DN150, OD: 168.3mm',
                'long_description' => "",
                'qty'              => 5,
                'rate'             => 271.60,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 13,
            ],
            14 => [
                'description'      => 'Compensator DN350 Custom made for Abrasive Powders - Length: 340mm',
                'long_description' => "",
                'qty'              => 7,
                'rate'             => 790.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 14,
            ],
            15 => [
                'description'      => 'Compensator DN200 Custom made for Abrasive Powders - Length: 340mm',
                'long_description' => "",
                'qty'              => 2,
                'rate'             => 710.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 15,
            ],
            16 => [
                'description'      => 'P&ID Tag 21-10 and 22-10 - Valve DN80',
                'long_description' => "including: Positioner (4-20 mA), Rubber Seal: Silicone red, (client ref.: Booster Valves)",
                'qty'              => 2,
                'rate'             => 1100.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 16,
            ],
            17 => [
                'description'      => 'Discount for delayed offer due to absence caused by private circumstances.',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => -150.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 17,
            ],
            18 => [
                'description'      => 'Payment 13 May 2026 and 2 June 2026',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => -7339.27,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 18,
            ],
        ],
    ],
];
