<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production invoice — TP Company Limited
 * Source: 2025-INV-118 Consolidated (refs INV-113/115/116/117/114)
 */
return [
    'key'                   => 'tp_inv_118',
    'source_invoice_number' => '2025-INV-118',
    'source_quote_ref'      => '2025-PQ-101',
    'related_proposal_key'  => '2.2025-PQ-101-vigor-extension',
    'customer_company'      => 'TP Company Limited',
    'force_status'          => 1,
    'save_option'           => 'otmain_seed_invoice_tp_inv_118',
    'invoice' => [
        'number'               => 118,
        'date'                 => '2025-06-30',
        'duedate'              => null,
        'expiry_days'          => 0,
        'status'               => 1,
        'document_title'       => 'Invoice',
        'invoice_title'        => 'Vigor Extension - Consolidated',
        'adminnote'            => '',
        'contact_person_name'  => 'S.A.Ibrahim',
        'contact_person_email' => 'inv@otmain.com',
        'contact_person_phone' => '+31618228651',
        'payment_terms_text'   => 'Before Departure',
        'delivery_terms'       => '',
        'lead_time'            => '',
        'delivery_address'     => "TP Company Limited\nBumbwini\nPO BOX 271 Zanzibar",
        'availability'         => '',
        'notes'                => '',
        'total_usd_display'    => '',
        'bank_account'         => 'EUR',
        'show_quantity_as'     => 1,
        'sale_agent'           => 0,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'adjustment'           => 0,
        'clientnote'           => 'We kindly request to transfer the amount before the Expiration date, mentioning the invoice number. Our general terms and conditions apply to all services.',
        'terms'                => '',
        'newitems'             => [
            1 => [
                'description'      => 'Ref.: INV-2025-113',
                'long_description' => "Vigor Shipunloader Delivery Extension Period: 19 May 2025 - 30 June 2025",
                'qty'              => 1,
                'rate'             => 3422.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => 'Ref.: INV-2025-115',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 2209.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'Ref.: INV-2025-116',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 2833.67,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => 'Ref.: INV-2025-117',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 2868.20,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => 'PLC Spareparts Ref.: 2025-INV-114',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 1351.29,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 5,
            ],
        ],
    ],
];
