<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production invoice — TP Company Limited
 * Source: 2026-INV-114 Atlas Copco Spare ZE6
 * Quote Ref → tp_otmsq_110
 */
return [
    'key'                   => 'tp_inv_114',
    'source_invoice_number' => '2026-INV-114 - Atlas Copco Spare - Vigor Shipunloader',
    'source_quote_ref'      => '10 - 2026 - OTMSQ - 110 - Spare Parts ZE6 Compressor - Vigor Ship Unloader',
    'related_proposal_key'  => 'tp_otmsq_110',
    'customer_company'      => 'TP Company Limited',
    'force_status'          => 1,
    'save_option'           => 'otmain_seed_invoice_tp_inv_114',
    'invoice' => [
        'number'               => 114,
        'date'                 => '2026-03-19',
        'duedate'              => '2026-03-21',
        'expiry_days'          => 2,
        'status'               => 1,
        'document_title'       => 'Commercial Invoice',
        'invoice_title'        => 'Atlas Copco Spare - Vigor Shipunloader',
        'adminnote'            => '',
        'contact_person_name'  => 'Widia Lestari - Ibrahim',
        'contact_person_email' => 'w.lestari@otmain.com',
        'contact_person_phone' => '+31620020563',
        'payment_terms_text'   => '100% before Shipment',
        'delivery_terms'       => '5-7 workdays',
        'lead_time'            => '',
        'delivery_address'     => "",
        'availability'         => '',
        'notes'                => 'PLEASE MENTION WITH YOUR TRANSACTION OUR INVOICE NUMBER. Freight estimate valid until 22 March; fuel/airline fluctuations adjusted on final invoice.',
        'total_usd_display'    => '$ 13.492,20',
        'bank_account'         => 'USD',
        'show_quantity_as'     => 1,
        'sale_agent'           => 0,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'adjustment'           => 0,
        'clientnote'           => '',
        'terms'                => '',
        'newitems'             => [
            1 => [
                'description'      => 'SKF BA1 7018 A AUSTRIA',
                'long_description' => "Spare Parts ZE6 Compressor – Vigor Ship Unloader",
                'qty'              => 1,
                'rate'             => 1890.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => 'SKF BA1 7018 B AUSTRIA',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 1890.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'Antivibration Pads (for 2 compressors)',
                'long_description' => "",
                'qty'              => 12,
                'rate'             => 127.05,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => '0663210808 - O-RING',
                'long_description' => "",
                'qty'              => 2,
                'rate'             => 9.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => '10663210326 - O-RING',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 165.77,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 5,
            ],
            6 => [
                'description'      => '10663210858 - O-RING',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 15.73,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 6,
            ],
            7 => [
                'description'      => 'Estimated Air Freight Cost – ZNZ (Zanzibar)',
                'long_description' => "Included in the Estimate: Export declaration fee, Handling charge, Doc fee\nNot Included: Clearance customs/ Delivery fee/ VAT fee in Zanzibar",
                'qty'              => 1,
                'rate'             => 6020.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 7,
            ],
        ],
    ],
];
