<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production invoice — TP Company Limited
 * Source: 2025-INV-119-BD Invoice Breakdown (CAO Rijk rates)
 */
return [
    'key'                   => 'tp_inv_119_bd',
    'source_invoice_number' => '2025-INV-119-BD',
    'source_quote_ref'      => '2025-PQ-101',
    'related_proposal_key'  => '2.2025-PQ-101-vigor-extension',
    'customer_company'      => 'TP Company Limited',
    'force_status'          => 1,
    'save_option'           => 'otmain_seed_invoice_tp_inv_119_bd',
    'invoice' => [
        'number'               => 119,
        'date'                 => '2025-07-02',
        'duedate'              => null,
        'expiry_days'          => 0,
        'status'               => 1,
        'document_title'       => 'Invoice Breakdown',
        'invoice_title'        => 'BD',
        'adminnote'            => '',
        'contact_person_name'  => 'S.A.Ibrahim',
        'contact_person_email' => 'inv@otmain.com',
        'contact_person_phone' => '+31618228651',
        'payment_terms_text'   => 'Before Departure',
        'delivery_terms'       => '',
        'lead_time'            => '',
        'delivery_address'     => "TP Company Limited\nBumbwini\nPO BOX 271 Zanzibar",
        'availability'         => '',
        'notes'                => 'Cost model per Official Dutch Government Law (CAO Rijk – Bijlage 6, Jan–Jun 2025). Source: https://www.caorijk.nl/cao-rijk/bijlage-6',
        'total_usd_display'    => '',
        'bank_account'         => 'EUR',
        'show_quantity_as'     => 1,
        'sale_agent'           => 0,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'adjustment'           => 0,
        'clientnote'           => 'We kindly request to transfer the amount before the Expiration date, mentioning the invoice number. Our general terms and conditions apply to all services.',
        'terms'                => '',
        'newitems'             => [
            1 => [
                'description'      => 'Accomodation (CAO Rijk - Other Place - Zanzibar)',
                'long_description' => "Vigor Shipunloader Delivery Extension\nPeriod: 19 May 2025 - 30 June 2025",
                'qty'              => 43,
                'rate'             => 423.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => 'Daily Allowance (Meals & Incidentals)',
                'long_description' => "",
                'qty'              => 43,
                'rate'             => 94.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'On Site Technical/ Project Supervision',
                'long_description' => "",
                'qty'              => 11,
                'rate'             => 400.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => 'Remote Work (Program, Design, Communication, Updates)',
                'long_description' => "",
                'qty'              => 6,
                'rate'             => 130.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => 'Local Transport, Internet,etc.',
                'long_description' => "Lump sum",
                'qty'              => 1,
                'rate'             => 450.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 5,
            ],
            6 => [
                'description'      => 'Admin,Emails, Communication, Overhead (10%)',
                'long_description' => "Lump sum",
                'qty'              => 1,
                'rate'             => 3892.10,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 6,
            ],
        ],
    ],
];
