<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production invoice — TP Company Limited
 * Source: 2026-INV-102 Commercial Spare Part (revised)
 * Quote Ref → 8.2025-SQ-107-vigor-spare-parts
 */
return [
    'key'                   => 'tp_inv_102',
    'source_invoice_number' => '2026-INV-102 - Vigor Shipunloader - Spare Part',
    'source_quote_ref'      => '2025-PQ-107- Vigor Shipunloader - Spare Parts',
    'related_proposal_key'  => '8.2025-SQ-107-vigor-spare-parts',
    'customer_company'      => 'TP Company Limited',
    'force_status'          => 1,
    'save_option'           => 'otmain_seed_invoice_tp_inv_102',
    'invoice' => [
        'number'               => 102,
        'date'                 => '2026-01-21',
        'duedate'              => '2026-02-11',
        'expiry_days'          => 21,
        'status'               => 1,
        'document_title'       => 'Commercial Invoice',
        'invoice_title'        => 'Vigor Shipunloader - Spare Part',
        'adminnote'            => '',
        'contact_person_name'  => 'Widia Lestari - Ibrahim',
        'contact_person_email' => 'w.lestari@otmain.com',
        'contact_person_phone' => '+31620020563',
        'payment_terms_text'   => '50% in advance 50% before delivery',
        'delivery_terms'       => '30 Days after the first Term Payment',
        'lead_time'            => '',
        'delivery_address'     => "--",
        'availability'         => '',
        'notes'                => 'The items revised later. Previously consisted of 4 × DN350; this has now been revised to 2 × DN350 and 2 × DN400',
        'total_usd_display'    => '$ 11.727,30',
        'bank_account'         => 'USD',
        'show_quantity_as'     => 1,
        'sale_agent'           => 0,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'adjustment'           => 0,
        'clientnote'           => '',
        'terms'                => '',
        'newitems'             => [
            1 => [
                'description'      => 'Valve (without actuator) Size: DN200',
                'long_description' => "",
                'qty'              => 2,
                'rate'             => 370.10,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => 'Spare Seat Viton',
                'long_description' => "",
                'qty'              => 4,
                'rate'             => 80.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'Valve (without actuator) Size: DN150',
                'long_description' => "",
                'qty'              => 2,
                'rate'             => 281.60,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => 'Spare Seat Viton',
                'long_description' => "",
                'qty'              => 4,
                'rate'             => 60.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => '5-Port Solenoid Valve SY9000 Series',
                'long_description' => "",
                'qty'              => 2,
                'rate'             => 121.80,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 5,
            ],
            6 => [
                'description'      => 'One Set proportional directional valves block assembled, Without solenoids',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 2336.92,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 6,
            ],
            7 => [
                'description'      => 'Twin solenoid for proportional directional valve',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 142.88,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 7,
            ],
            8 => [
                'description'      => 'Seal kit for valve section SL 3',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 91.84,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 8,
            ],
            9 => [
                'description'      => 'Sealkit for connection block PSL BG 3',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 68.32,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 9,
            ],
            10 => [
                'description'      => 'Alternative Hydropack Oil Reservior Breather',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 186.10,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 10,
            ],
            11 => [
                'description'      => 'Temprature Sensor 4-20mA, scale 0-150 degree',
                'long_description' => "",
                'qty'              => 3,
                'rate'             => 257.60,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 11,
            ],
            12 => [
                'description'      => 'Waterpump and Cooling Pump',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 1260.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 12,
            ],
            13 => [
                'description'      => 'Compensator DN350',
                'long_description' => "Revised mix with DN400 (was 4× DN350)",
                'qty'              => 2,
                'rate'             => 860.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 13,
            ],
            14 => [
                'description'      => 'Compensator DN400',
                'long_description' => "Revised mix with DN350 (was 4× DN350)",
                'qty'              => 2,
                'rate'             => 945.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 14,
            ],
            15 => [
                'description'      => 'Algen dissolver',
                'long_description' => "",
                'qty'              => 3,
                'rate'             => 55.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 15,
            ],
            16 => [
                'description'      => 'Discount',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => -750.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 16,
            ],
        ],
    ],
];
