<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Production invoice — TP Company Limited
 * Source: 2025-INV-126 Service Trip
 * Quote Ref PQ-104/106 → 5.2025-PQ-104 + 7.2025-PQ-106
 */
return [
    'key'                   => 'tp_inv_126',
    'source_invoice_number' => '2025-INV-126-Vigor Shipunloader-Service Trip',
    'source_quote_ref'      => '2025-PQ-104/106-Vigor Shipunloader-Service Trip',
    'related_proposal_key'  => '5.2025-PQ-104-vigor-service-trip',
    'related_proposal_keys' => ['5.2025-PQ-104-vigor-service-trip', '7.2025-PQ-106-vigor-service-trip'],
    'customer_company'      => 'TP Company Limited',
    'force_status'          => 1,
    'save_option'           => 'otmain_seed_invoice_tp_inv_126',
    'invoice' => [
        'number'               => 126,
        'date'                 => '2025-12-11',
        'duedate'              => null,
        'expiry_days'          => 0,
        'status'               => 1,
        'document_title'       => 'Invoice',
        'invoice_title'        => 'Vigor Shipunloader-Service Trip',
        'adminnote'            => '',
        'contact_person_name'  => 'Widia Lestari - Ibrahim',
        'contact_person_email' => 'w.lestari@otmain.com',
        'contact_person_phone' => '+31620020563',
        'payment_terms_text'   => '100% Before Departure',
        'delivery_terms'       => 'EXW',
        'lead_time'            => '',
        'delivery_address'     => "-",
        'availability'         => '',
        'notes'                => 'The Remaining Working Days will be added to the last Invoice',
        'total_usd_display'    => '',
        'bank_account'         => 'EUR',
        'show_quantity_as'     => 1,
        'sale_agent'           => 0,
        'discount_type'        => '',
        'discount_percent'     => 0,
        'discount_total'       => 0,
        'adjustment'           => 0,
        'clientnote'           => 'We kindly request to transfer the amount before the Expiration date, mentioning the invoice number. Our general terms and conditions apply to all services.',
        'terms'                => '',
        'newitems'             => [
            1 => [
                'description'      => 'Option 1: Flexible Service (Ref.: 2025-PQ-104-Vigor Shipunloader-Service Trip)',
                'long_description' => "Vigor Shipunloader Service Trip from 23 October to 15 December.",
                'qty'              => 1,
                'rate'             => 7407.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 1,
            ],
            2 => [
                'description'      => 'Working Days: 12 Days',
                'long_description' => "24/10, 25/10, 1/11, 3/11, 9/11, 12/11, 14/11, 15/11, 17/11, 18/11, 20/11, 21/11",
                'qty'              => 12,
                'rate'             => 350.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 2,
            ],
            3 => [
                'description'      => 'Option 1: Flexible Service (Ref.: 2025-PQ-106-Vigor Shipunloader-Service Trip)',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => 4317.60,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 3,
            ],
            4 => [
                'description'      => 'Working Days: 6 Days',
                'long_description' => "24/11, 30/11, 2/12, 3/12, 08/12, 10/12",
                'qty'              => 6,
                'rate'             => 350.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 4,
            ],
            5 => [
                'description'      => 'Discount: Ground Transportation',
                'long_description' => "",
                'qty'              => 18,
                'rate'             => -25.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 5,
            ],
            6 => [
                'description'      => 'Discount: 1 Working Day (30/11) Free of Charge: Crane Inspection',
                'long_description' => "",
                'qty'              => 1,
                'rate'             => -350.00,
                'unit'             => '',
                'taxname'          => [],
                'order'            => 6,
            ],
        ],
    ],
];
